config/routes.rb
Rails.application.routes.draw do

 root "home#index", as: :home
resources :users, only: [:new, :create]
resources :sessions, only: [:new, :create] do
  delete :destroy, on: :collection
end

resources :products do
   resources :reviews, only: [:create, :destroy]
   resources :favourites, only: [:create, :destroy]

 end

end

app/models/product.rb
class Product < ActiveRecord::Base
has_many :reviews, dependent: :destroy
belongs_to :category
belongs_to :user
before_validation :set_default_price
has_many :favourites, dependent: :destroy
has_many :users, through: :favourites

  validates :price, {presence: true}
  validates :title, presence: true, uniqueness: true

  validates :sale_price, presence: true, numericality: {less_than_or_equal_to: :price}

    # after_validation :set_default_price
  def on_sale?
    price > sale_price
  end

  def user_full_name
    user ? user.full_name : ""
  end

  def self.search(search)
    where("title ILIKE ? OR description ILIKE ?", "%#{search}%", "%#{search}%")
  end

  def favourite_for(user)
    favourites.find_by_user_id user if user
  end

  private

  def set_default_price
  #   if sale_price.nil?
  #     sale_price = price
  #   else
  #     sale_price
  #   end
    self.sale_price ||= price
  end

  def titleize_title
  self.title = title.titleize
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

before_action :authenticate_user!, except: [:index, :show]
before_action(:find_product, {only: [:show, :edit, :update, :destroy]})

 #original controllers
  def new
    @product = Product.new
  end

  def create
    product_params = params.require(:product).permit([:title, :description, :price, :category_id])
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      flash[:notice] = "Product created!"
      redirect_to product_path(@product)
    else
      flash[:alert] = "Didn't save product!"
      render :new
    end
  end

  def show
    @product = Product.find params[:id]
    @review = Review.new

  end

  def index
    @products = Product.all
    if params[:search]
      @products = Product.search(params[:search]).order("created_at DESC")
    else
      @products = Product.all.order('created_at DESC')
    end
    @products = @products.page(params[:page]).per(20)

  end

  def edit
    @product = Product.find params[:id]
  end

  def update
    @product  = Product.find params[:id]
    product_params = params.require(:product).permit([:title, :description, :price])
    if @product.update product_params
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to products_path
  end

  private

def product_params
  product_params = params.require(:product).permit([:title, :description])
end

def find_product
  @product = Product.find params[:id]
end
#   def new
#     @product = Product.new
#   end
#
#   def create
#     @product = Product.new
#   end
#
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= @product.errors.full_messages.join(", ") %>

<%= form_for @product do |f| %>
  <div>
    <br>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.text_area :price %>
  </div>

  <%= f.submit %>
<% end %>

app/views/products/index.html.erb
<h1>Products</h1>

<%= form_tag(products_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Products" %>
<%= submit_tag "Search" %>
<% end %>

<% @products.each do |product| %>

<div>
  <%= link_to product.title, product_path(product) %>
</div>

<% end %>

<%= paginate @products %>
<%= page_entries_info @products %>

app/views/products/new.html.erb
<h1>Creating new product</h1>

<%= @product.errors.full_messages.join("").html_safe %>

<%= form_for @product do |f| %>

<div>
<br>
<%= f.label :title %>
<%= f.text_field :title %>
</div>

<div>
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name %>
</div>

<div>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>

</div>

<br>
<div>
  <%= f.label :price %>
  <%= f.text_field :price %>
</div>
<br>

  <%= f.submit %>

<% end %>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>
<p><%= @product.description %></p>
<p>Created By: <%= @product.user_full_name.titleize %></p>

<p>Price: $<%= "%.2f" % @product.price %></p>
<% if can? :edit, @product %>
<%= link_to "Edit", edit_product_path(@product) %>
<% end %>
<% if can? :destroy, @product %>
<%= link_to "Delete", product_path(@product), method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>

<% favourite = @product.favourite_for(current_user) %>
<% if user_fave %>
  <%= link_to "Un-fave", product_favourite_path(@product, user_fave), method: :delete %>
<% else %>
  <%= link_to "Favourite", product_favourites_path(@product), method: :post %>
<% end %>
(<%= @product.favourites.count %>)
<hr>

<%= @review.errors.full_messages.join(", ") %>
<%#= form_helper @answer, url: product_reviews_path(@product) do |form_helper|%>
<%= form_for [@product, @review] do |form_helper| %>
<label for="review_stars" class="control-label">Rate This</label>
<input id="review_stars" name="review[stars]" class="rating rating-loading" data-min="0" data-max="5" data-step="0.5" data-show-clear="false">

<br>
<%= form_helper.label :body, "Review" %>
<br>
<%= form_helper.text_area :body %>
<br>
<%= form_helper.submit %>

<% end %>

<h2>Review</h2>
<% @product.reviews.each do |ans| %>
<hr>
<i class="fa fa-star icon-yellow-star" aria-hidden="true"></i>
<i class="fa fa-star icon-yellow-star" aria-hidden="true"></i>
<i class="fa fa-star icon-yellow-star" aria-hidden="true"></i>
  <%= ans.stars %>
  <%= ans.body %>
  by: <%= ans.user_full_name.titleize %>
<br>
  <% if can? :destroy, ans %>
<%= link_to "delete", product_review_path(@product, ans),
                                  data: {confirm: "Are you sure?"}, method: :delete%>
<% end %>
<% end %>

<script>
  $(".rating").rating();
</script>