config/routes.rb
Rails.application.routes.draw do

 root "home#index", as: :home
resources :users, only: [:new, :create]
resources :sessions, only: [:new, :create] do
  delete :destroy, on: :collection
end

resources :products do
   resources :reviews, only: [:create, :destroy]
   resources :favourites, only: [:create, :destroy]

 end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amaze-On</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="icon" href="http://www.communications-ink.net/wp-content/uploads/2015/03/Screen-Shot-2015-03-10-at-2.51.37-PM.png"</link>

</head>
<body>

<%= link_to "Home", home_path %>
|
<% if user_signed_in? %>

  <%= link_to "New Products", new_product_path %>
  |
  <%= link_to "List Products", products_path %>
  |
  <%= link_to "Log out", sessions_path, method: :delete %>
  |
  Hello <%= current_user.first_name.titleize %>!
<% else %>
  <%= link_to "Sign In", new_session_path %>
  |
  <%= link_to "Sign Up", new_user_path %>
  <% end %>
<hr>
<%= notice || alert %>
<hr>
<%= yield %>

<img src="http://media.corporate-ir.net/media_files/IROL/97/97664/images/amazon_logo_RGB.jpg" alt="" />
</body>
</html>